Import('env')
from os import path

# --------------------------------------------------------------------------
name       = 'mcrt_messages'
sources    = env.DWAGlob('*.cc')
incdir     = ['$INSTALL_DIR/include']
components = [
            'arras4_log',
            'message_api',
            'jsoncpp'
]
# --------------------------------------------------------------------------
publicHeaders = [
    'BaseFrame.h',
    'CreditUpdate.h',
    'JSONMessage.h',
    'JSONUtils.h',
    'GenericMessage.h',
    'GeometryObjects.h',
    'GeometryData.h',
    'OutputRates.h',
    'PartialFrame.h',
    'ProgressiveFeedback.h',
    'ProgressiveFrame.h',
    'ProgressMessage.h',
    'RDLMessage.h',
    'RDLMessage_LeftEye.h',
    'RDLMessage_RightEye.h',
    'RenderedFrame.h',
    'RenderMessages.h',
    'ViewportMessage.h'
]
env.DWAInstallInclude(publicHeaders, 'mcrt_messages')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAInstallComponent(name, LIBS=[target], CPPPATH=incdir, COMPONENTS=components)
env.DWALinkValidate(name)
